export class StockWms {
  contentStatus:string;
  product:string;
  materialNumber:string;
  sapLoc:string;
  dryDate:string;
  matType:string;
  bin:string;
  labelNr:string;
  stockMarket:string;
  prNetWeight:string;
  prWeightUnit:string;
  qty:string;
  rackType:string;
  plant:string;
  delivery:string;
  prodAdd:string;
  prodDsc2:string;
  serialNr:string;
  batchNr:string;
  market:string;
  rackId:string;
  chckQty:string;
  } 